// Auto-generated by Arduino CLI Wrapper: Source Backup
#pragma once
#include <stddef.h>
#include <stdint.h>

#if __has_include(<Arduino.h>)
#include <Arduino.h>
#endif

namespace sourcebackup {

extern const uint8_t blob[];
extern const size_t blob_len;

struct View {
  const uint8_t* manifest;
  uint32_t manifest_len;
  const uint8_t* archive;
  uint32_t archive_len;
  uint16_t version;
  uint16_t flags;
  bool valid;
};

bool parse(View& out);
bool isValid();

const uint8_t* manifestPtr();
uint32_t manifestLength();

const uint8_t* archivePtr();
uint32_t archiveLength();

bool writeRawTo(Print& out);
bool writeBlobBase64To(Print& out);
bool writeArchiveBase64To(Print& out);
bool printRestoreUrl(Print& out);
bool writeArchiveBase64WithInfoTo(Print& out);

}  // namespace sourcebackup
